---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: openshift-tektoncd-pipeline-run
spec:
  pipelineSpec:
     params:
       - name: repo_url
       - name: revision
     workspaces:
     - name: source
     tasks:
       - name: fetch
         taskRef:
           name: git-clone
         params:
           - name: url
             value: $(params.repo_url)
           - name: revision
             value: $(params.revision)
         workspaces:
           - name: output
             workspace: source
       - name: run-tests
         runAfter: [fetch]
         taskSpec:
           workspaces:
             - name: source
           steps:
             - image: registry.access.redhat.com/ubi8/go-toolset:1.14
               name: run-tests
               workingdir: $(workspaces.source.path)
               script: |
                 #!/usr/bin/env bash
                 # install kubectl/oc
                 mkdir -p /opt/app-root/src/bin
                 curl -sL -o- https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | \
                 tar xvzf - -C /opt/app-root/src/bin oc kubectl  && \
                 chmod +x /opt/app-root/src/bin/{kubectl,oc}
    
                 # Don't install pipelines in here use the local one
                 export E2E_DEBUG=true
                 source $(git rev-parse --show-toplevel)/test/e2e-common.sh
                 
                 # Run the integration tests
                 header "Running Go e2e tests"
                 go_test_e2e -timeout=20m ./test/... || failed=1

                 # Run these _after_ the integration tests b/c they don't quite work all the way
                 # and they cause a lot of noise in the logs, making it harder to debug integration
                 # test failures.
                 go_test_e2e -tags=examples -timeout=20m ./test/ || failed=1
                 
                 (( failed )) && fail_test
                 success                 

                 
         workspaces:
           - name: source
             workspace: source
  params:
    - name: repo_url
      value: {{repo_url}}
    - name: revision
      value: {{revision}}
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
